- name: New Debian Setup
  hosts: localhost
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
  become: true
  become_method: su
  become_user: "{{ ansible_user }}"
  tasks:
    - name: Loading package lists from YAML file... 
      include_vars:
        file: package-list.yml

    - name: Debug ansible_user check
      debug:
        var: ansible_user

    - name: Updating apt cache
      apt:
        update_cache: yes

    - name: Installing apt packages from YAML file
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages }}"

    - name: Gathering system package facts
      package_facts:
        manager: auto

    - name: Installing snapd if it's not installed
      apt:
        name: snapd
        state: present
      when: "'snap' not in ansible_facts.packages"

    - name: Installing snap packages
      ansible.builtin.command:
        cmd: "snap install {{ item }}"
      loop: "{{ snap_packages }}"
      become: true
      when: "'snapd' in ansible_facts.packages"
