- name: New Debian Setup
  hosts: localhost
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"    
    apt_packages:
      - cmake
      - curl
      - fonts-font-awesome
      - g++
      - gettext
      - gh
      - git
      - libtool-bin
      - lolcat
      - locate
      - mdbtools
      - ninja-build
      - pkg-config
      - powershell
      - python3-venv
      - shellcheck
      - tmux
      - unzip
      - zsh
    snap_packages:
      - brave
      - firefox
      - gitkraken
      - glow
      - telegram-desktop
  become: true
  become_method: su
  become_user: "{{ ansible_user }}"
  tasks:
    - name: Debug ansible_user
      debug:
        var: ansible_user

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages via apt
      apt:
        name: "{{ apt_packages }}"
        state: present

    - name: Gather system package facts
      package_facts:
        manager: auto

    - name: Install snapd package if snap is not installed
      apt:
        name: snapd
        state: present
      when: "'snap' not in ansible_facts['packages']"

    - name: Install snap packages
      community.general.snap:
        name: "{{ item }}"
        state: present
      loop: "{{ snap_packages }}"
      when: "'snap' in ansible_facts.packages"

    - name: Install apt packages again after installing snapd
      apt:
        name: "{{ apt_packages }}"
        state: present
      when: "'snap' not in ansible_facts['packages']"
