apt_packages:
  - cmake
  - curl
  - fd-find
  - fonts-font-awesome
  - g++
  - gettext
  - gh
  - git
  - libtool-bin
  - lolcat
  - locate
  - mdbtools
  - ninja-build
  - pkg-config
  - powershell
  - python3-venv
  - ripgrep
  - shellcheck
  - tmux
  - unzip
  - zsh
snap_packages:
  - brave
  - firefox
  - gitkraken
  - glow
  - telegram-desktop
dir_list:
  - bin
  - build
  - hax
  - tmp
  - .local/bin
  - .config/shell
add_to_path:
  - $HOME/bin
  - $HOME/.local/bin

